# -*- coding: utf-8 -*-
"""MachineLearning_Individual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HFHq3sFaFJnYmW8OLyzNm432vlW9U1TM
"""

!pip install imbalanced-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from imblearn.over_sampling import ADASYN
from scipy import stats

df = pd.read_csv('/content/drive/MyDrive/DATASET/agriculture_dataset.csv').dropna()

numeric_df = df.select_dtypes(include=[np.number])
z_scores = np.abs(stats.zscore(numeric_df))
df = df[(z_scores < 3).all(axis=1)]


df['Green_Stress'] = df['NDVI'] / (df['Chlorophyll_Content'] + 0.1)
df['Thermal_Moisture'] = df['Thermal_Images'] * df['Soil_Moisture']


noise = ['GPS_Coordinates', 'Field_Boundaries', 'Bounding_Boxes', 'Ground_Truth_Segmentation']
df_clean = df.drop(columns=[c for c in noise if c in df.columns])


df_encoded = pd.get_dummies(df_clean, columns=['Crop_Type', 'Crop_Growth_Stage'], drop_first=True)

X = df_encoded.drop('Crop_Health_Label', axis=1)
y = df_encoded['Crop_Health_Label']

balancing = ADASYN(random_state=42)
X_res, y_res = balancing.fit_resample(X, y)

X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size=0.2, random_state=42)

scaler = RobustScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


selector_model = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=42)
selector_model.fit(X_train_scaled, y_train)


importances = selector_model.feature_importances_
top_indices = np.argsort(importances)[-12:]

X_train_selected = X_train_scaled[:, top_indices]
X_test_selected = X_test_scaled[:, top_indices]


print("Training Model :>")
model = RandomForestClassifier(
    n_estimators=150,
    max_depth=12,
    n_jobs=-1,
    random_state=42
)
model.fit(X_train_selected, y_train)


y_pred = model.predict(X_test_selected)

print("\n--- FINAL CLASSIFICATION RESULTS ---")
print(f"Overall Accuracy: {accuracy_score(y_test, y_pred):.2f}")
print("\nDetailed Metrics (Precision, Recall, F1):")
print(classification_report(y_test, y_pred))

plt.figure(figsize=(8, 6))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='YlGnBu',
            xticklabels=['Unhealthy (0)', 'Healthy (1)'],
            yticklabels=['Unhealthy (0)', 'Healthy (1)'])
plt.title('Random Forest: Final Health Classification Results')
plt.xlabel('Drone Prediction')
plt.ylabel('Actual Status')
plt.show()

plt.figure(figsize=(10, 6))
feat_importances = pd.Series(importances[top_indices], index=X.columns[top_indices])
feat_importances.nlargest(12).plot(kind='barh', color='teal')
plt.title('Top 12 Features Influencing Drone Decisions')
plt.show()

